
 const emergencyItem=[
     {
    "id": 11,
    "name": "Raja Garden",
    "code": "EE S1",
    "image": null,
    "pincode": null,
    "phoneNumber": "912564124",
    "address": "",
    "latitude": 28.62630785,
    "longitude": 77.2090851,
    "geofenceColour": null,
    "geofenceType": null,
    "radius": null,
    "userCount": 0,
    "stoppageAllowed": false,
    "stoppageHour": 0,
    "stoppageMin": 0,
    "zoomLevel": null,
    "parentSiteId": null,
    "parentSite": null,
    "coordinatesDTOList": [],
    "entryAlertUserList": [],
    "exitAlertUserList": [],
    "companyId": 1,
    "siteTypeId": null,
    "createdAt": null,
    "createdBy": null,
    "updatedAt": "2022-01-25T06:47:00.000+00:00",
    "updatedBy": null,
    "isActive": true,
    "roles": null,
    "siteTypeDTO": {
        "id": 1,
        "name": "HO",
        "isActive": true
    },
    "subSiteDTOList": [],
    "allocatedVehicle": 1,
    "gpsInstalled": 0,
    "vehicleCount": 0,
    "zoneId": null,
    "zoneName":" Zone VI",
    "vendorCount": 1,
    "fplList": [],
    "userDTOs": [],
    "type": null,
    "siteHierarchy": [],
    "hierarchyList": null
},
{
    "id": 12,
    "name": "Mohan Garden",
    "code": "EE W-II C",
    "image": null,
    "pincode": null,
    "phoneNumber": "9225641234",
    "address": "",
    "latitude": 28.62630785,
    "longitude": 77.2090851,
    "geofenceColour": null,
    "geofenceType": null,
    "radius": null,
    "userCount": 0,
    "stoppageAllowed": false,
    "stoppageHour": 0,
    "stoppageMin": 0,
    "zoomLevel": null,
    "parentSiteId": null,
    "parentSite": null,
    "coordinatesDTOList": [],
    "entryAlertUserList": [],
    "exitAlertUserList": [],
    "companyId": 1,
    "siteTypeId": null,
    "createdAt": null,
    "createdBy": null,
    "updatedAt": "2022-01-25T06:47:00.000+00:00",
    "updatedBy": null,
    "isActive": true,
    "roles": null,
    "siteTypeDTO": {
        "id": 1,
        "name": "HO",
        "isActive": true
    },
    "subSiteDTOList": [],
    "allocatedVehicle": 1,
    "gpsInstalled": 0,
    "vehicleCount": 0,
    "zoneId": null,
    "zoneName": "Zone III",
    "vendorCount": 1,
    "fplList": [],
    "userDTOs": [],
    "type": null,
    "siteHierarchy": [],
    "hierarchyList": null
},
{
    "id": 13,
    "name": "Kirti Nagar",
    "code":"WW SW-II c",
    "image": null,
    "pincode": null,
    "phoneNumber": "9435641234",
    "address": "",
    "latitude": 28.62630785,
    "longitude": 77.2090851,
    "geofenceColour": null,
    "geofenceType": null,
    "radius": null,
    "userCount": 0,
    "stoppageAllowed": false,
    "stoppageHour": 0,
    "stoppageMin": 0,
    "zoomLevel": null,
    "parentSiteId": null,
    "parentSite": null,
    "coordinatesDTOList": [],
    "entryAlertUserList": [],
    "exitAlertUserList": [],
    "companyId": 1,
    "siteTypeId": null,
    "createdAt": null,
    "createdBy": null,
    "updatedAt": "2022-01-25T06:47:00.000+00:00",
    "updatedBy": null,
    "isActive": true,
    "roles": null,
    "siteTypeDTO": {
        "id": 1,
        "name": "HO",
        "isActive": true
    },
    "subSiteDTOList": [],
    "allocatedVehicle": 1,
    "gpsInstalled": 0,
    "vehicleCount": 0,
    "zoneId": null,
    "zoneName": "zone II",
    "vendorCount": 1,
    "fplList": [],
    "userDTOs": [],
    "type": null,
    "siteHierarchy": [],
    "hierarchyList": null
},
{
    "id": 14,
    "name": "Rajauri Garden",
    "code": "EE c-II",
    "image": null,
    "pincode": null,
    "phoneNumber": "9655641234",
    "address": "",
    "latitude": 28.62630785,
    "longitude": 77.2090851,
    "geofenceColour": null,
    "geofenceType": null,
    "radius": null,
    "userCount": 0,
    "stoppageAllowed": false,
    "stoppageHour": 0,
    "stoppageMin": 0,
    "zoomLevel": null,
    "parentSiteId": null,
    "parentSite": null,
    "coordinatesDTOList": [],
    "entryAlertUserList": [],
    "exitAlertUserList": [],
    "companyId": 1,
    "siteTypeId": null,
    "createdAt": null,
    "createdBy": null,
    "updatedAt": "2022-01-25T06:47:00.000+00:00",
    "updatedBy": null,
    "isActive": true,
    "roles": null,
    "siteTypeDTO": {
        "id": 1,
        "name": "HO",
        "isActive": true
    },
    "subSiteDTOList": [],
    "allocatedVehicle": 1,
    "gpsInstalled": 0,
    "vehicleCount": 0,
    "zoneId": null,
    "zoneName": "zone I",
    "vendorCount": 1,
    "fplList": [],
    "userDTOs": [],
    "type": null,
    "siteHierarchy": [],
    "hierarchyList": null
},
{
    "id": 15,
    "name": "Uttam Nagar",
    "code": "EE s-I",
    "image": null,
    "pincode": null,
    "phoneNumber": "9875641234",
    "address": "",
    "latitude": 28.62630785,
    "longitude": 77.2090851,
    "geofenceColour": null,
    "geofenceType": null,
    "radius": null,
    "userCount": 0,
    "stoppageAllowed": false,
    "stoppageHour": 0,
    "stoppageMin": 0,
    "zoomLevel": null,
    "parentSiteId": null,
    "parentSite": null,
    "coordinatesDTOList": [],
    "entryAlertUserList": [],
    "exitAlertUserList": [],
    "companyId": 1,
    "siteTypeId": null,
    "createdAt": null,
    "createdBy": null,
    "updatedAt": "2022-01-25T06:47:00.000+00:00",
    "updatedBy": null,
    "isActive": true,
    "roles": null,
    "siteTypeDTO": {
        "id": 1,
        "name": "HO",
        "isActive": true
    },
    "subSiteDTOList": [],
    "allocatedVehicle": 1,
    "gpsInstalled": 0,
    "vehicleCount": 0,
    "zoneId": null,
    "zoneName": "zone V",
    "vendorCount": 1,
    "fplList": [],
    "userDTOs": [],
    "type": null,
    "siteHierarchy": [],
    "hierarchyList": null
},
{
    "id": 16,
    "name": "Dwarka Mor",
    "code": "EE W-II C",
    "image": null,
    "pincode": null,
    "phoneNumber": "9544641234",
    "address": "",
    "latitude": 28.62630785,
    "longitude": 77.2090851,
    "geofenceColour": null,
    "geofenceType": null,
    "radius": null,
    "userCount": 0,
    "stoppageAllowed": false,
    "stoppageHour": 0,
    "stoppageMin": 0,
    "zoomLevel": null,
    "parentSiteId": null,
    "parentSite": null,
    "coordinatesDTOList": [],
    "entryAlertUserList": [],
    "exitAlertUserList": [],
    "companyId": 1,
    "siteTypeId": null,
    "createdAt": null,
    "createdBy": null,
    "updatedAt": "2022-01-25T06:47:00.000+00:00",
    "updatedBy": null,
    "isActive": true,
    "roles": null,
    "siteTypeDTO": {
        "id": 1,
        "name": "HO",
        "isActive": true
    },
    "subSiteDTOList": [],
    "allocatedVehicle": 1,
    "gpsInstalled": 0,
    "vehicleCount": 0,
    "zoneId": null,
    "zoneName": "zone VI",
    "vendorCount": 1,
    "fplList": [],
    "userDTOs": [],
    "type": null,
    "siteHierarchy": [],
    "hierarchyList": null
},
{
    "id": 17,
    "name": "Dwarka Mor",
    "code": "EE W-II C",
    "image": null,
    "pincode": null,
    "phoneNumber": "9544641234",
    "address": "",
    "latitude": 28.62630785,
    "longitude": 77.2090851,
    "geofenceColour": null,
    "geofenceType": null,
    "radius": null,
    "userCount": 0,
    "stoppageAllowed": false,
    "stoppageHour": 0,
    "stoppageMin": 0,
    "zoomLevel": null,
    "parentSiteId": null,
    "parentSite": null,
    "coordinatesDTOList": [],
    "entryAlertUserList": [],
    "exitAlertUserList": [],
    "companyId": 1,
    "siteTypeId": null,
    "createdAt": null,
    "createdBy": null,
    "updatedAt": "2022-01-25T06:47:00.000+00:00",
    "updatedBy": null,
    "isActive": true,
    "roles": null,
    "siteTypeDTO": {
        "id": 1,
        "name": "HO",
        "isActive": true
    },
    "subSiteDTOList": [],
    "allocatedVehicle": 1,
    "gpsInstalled": 0,
    "vehicleCount": 0,
    "zoneId": null,
    "zoneName": "zone VI",
    "vendorCount": 1,
    "fplList": [],
    "userDTOs": [],
    "type": null,
    "siteHierarchy": [],
    "hierarchyList": null
}
]


module.exports=emergencyItem

